"""

Message: add_title
Revision ID: 714412c9521c
Revises: 19aa1dbf7917
Create Date: 2020-10-21 18:25:38.647658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714412c9521c'
down_revision = '19aa1dbf7917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_lists', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
